/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grocery_shop_sample_1;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DILUSHA LAKSHAN
 */
public class Manage_GRN extends javax.swing.JFrame {

    HashMap<String, GRNItem> grnItemMap = new HashMap<>();
    private String productID;

    /**
     * Creates new form Manage_GRN
     */
    public Manage_GRN() {
        initComponents();
        //loadProductName();
        loadSupplierEmail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtRetailPrice = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        cmbSupplierEmail = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGRNData = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        btnSaveGRN = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        btnSelectProduct = new javax.swing.JButton();
        lblEmployee = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE GRN");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel2.setText("Product Name :");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel3.setText("Retail Price");

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel4.setText("Quantity");

        btnAdd.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnAdd.setText("ADD TO GRN");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnUpdate.setText("UPDATE");

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel5.setText("Supplier Email");

        txtRetailPrice.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtQuantity.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        cmbSupplierEmail.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        tblGRNData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Quantity", "Retail Price", "ID"
            }
        ));
        jScrollPane1.setViewportView(tblGRNData);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel7.setText("Amount");

        lblAmount.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblAmount.setText("0.0");

        btnSaveGRN.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnSaveGRN.setText("SAVE GRN");
        btnSaveGRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveGRNActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel12.setText("Product Category :");

        lblCategory.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N

        btnSelectProduct.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        btnSelectProduct.setText("SELECT PRODUCT");
        btnSelectProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectProductActionPerformed(evt);
            }
        });

        lblEmployee.setText("dilusha");

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\Images\\AURORA.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRetailPrice)
                                            .addComponent(txtQuantity)
                                            .addComponent(cmbSupplierEmail, 0, 136, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(btnSelectProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmployee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(252, 252, 252)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveGRN, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(188, 188, 188)
                                .addComponent(lblAmount)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployee)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSelectProduct))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtRetailPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbSupplierEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addGap(13, 13, 13)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnSaveGRN)
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String proName = String.valueOf(lblName.getText());
            Double retailPrice = Double.valueOf(txtRetailPrice.getText());
            int quantity = Integer.valueOf(txtQuantity.getText());
            String supplier = String.valueOf(cmbSupplierEmail.getSelectedItem());

            if (txtRetailPrice.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(rootPane, "Enter the Retail Price");
            } else if (retailPrice <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Enter the correct retail price");
            } else if (txtQuantity.getText().isEmpty() == true) {
                JOptionPane.showMessageDialog(rootPane, "Enter the Quantity");
            } else if (quantity <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Enter the correct quantity");
            } else if (supplier.isEmpty() == true) {
                JOptionPane.showMessageDialog(rootPane, "Select the supplier");
            } else {

                GRNItem grnObj = new GRNItem();
                grnObj.setProName(proName);
                grnObj.setQuantity(quantity);
                grnObj.setRetailPrice(retailPrice);
                grnObj.setProductID(productID);

                grnItemMap.put(proName, grnObj);
                loadGRNItems();
                calculateSum();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveGRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveGRNActionPerformed
        try {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();
            String dateAndTime = String.valueOf(now);

            double amount = Double.valueOf(lblAmount.getText());
            String supplier = String.valueOf(cmbSupplierEmail.getSelectedItem());
            double retailPr = Double.valueOf(txtRetailPrice.getText());
            int quantity = Integer.valueOf(txtQuantity.getText());

            //insert data to the grn table
            ResultSet grnRS1 = dbConnection.execute("INSERT INTO `grn` (`purchase_date_time`,`paid_amount`,`employee_userName`,`supplier_email`) VALUES ('" + dateAndTime + "','" + amount + "','" + String.valueOf(lblEmployee.getText()) + "','" + supplier + "')");

            //get the id of the last inserted record from the grn table
            ResultSet grnRS2 = dbConnection.execute("SELECT * FROM `grn` ORDER BY `id` DESC LIMIT 1");
            if (grnRS2.next()) {
                long grnID = grnRS2.getLong("id");

                DefaultTableModel model = (DefaultTableModel) tblGRNData.getModel();
                for (int row = 0; row < model.getRowCount(); row++) {
                    int proID = Integer.valueOf(model.getValueAt(row, 3).toString());

                    //get stockID from the stock table according to the productID
                    ResultSet stockRS = dbConnection.execute("SELECT * FROM `stock` WHERE `product_code`='" + proID + "'");
                    if (stockRS.next()) {
                        long stockID = stockRS.getLong("id");

                        //insert data to grnItem table
                        ResultSet grnItemRS = dbConnection.execute("INSERT INTO `grn_item` (`quantity`,`retail_price`,`stock_id`,`grn_id`) VALUES ('" + Integer.valueOf(model.getValueAt(row, 1).toString()) + "','" + Double.valueOf(model.getValueAt(row, 2).toString()) + "','" + stockID + "','" + grnID + "')");
                    }
                }
                JOptionPane.showMessageDialog(rootPane, "Insertion Successful");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnSaveGRNActionPerformed

    private void btnSelectProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectProductActionPerformed
        // TODO add your handling code here:

        Products products = new Products(this);
        products.setVisible(true);
    }//GEN-LAST:event_btnSelectProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_GRN().setVisible(true);
            }
        });
    }

    //load grn detail to the jTable
    private void loadGRNItems() {
        DefaultTableModel model = (DefaultTableModel) tblGRNData.getModel();
        model.setRowCount(0);
        for (GRNItem grnItem : grnItemMap.values()) {
            Vector<String> vector = new Vector<>();
            vector.add(grnItem.getProName());
            vector.add(String.valueOf(grnItem.getQuantity()));
            vector.add(String.valueOf(grnItem.getRetailPrice()));
            vector.add(String.valueOf(grnItem.getProductID()));
            model.addRow(vector);
            tblGRNData.setModel(model);
        }
    }

    //load supplier email to the combobox
    private void loadSupplierEmail() {
        try {
            ResultSet supplierRS = dbConnection.execute("SELECT * FROM `supplier`");
            while (supplierRS.next()) {
                String email = supplierRS.getString("email");
                cmbSupplierEmail.addItem(email);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    //calculate the amount of all products
    private void calculateSum() {
        int numRows = tblGRNData.getRowCount();
        double amount = 0.0;

        for (int i = 0; i < numRows; i++) {
            double quantity = Double.valueOf(tblGRNData.getValueAt(i, 1).toString());
            double unitPrice = Double.valueOf(tblGRNData.getValueAt(i, 2).toString());

            double total = quantity * unitPrice;
            amount += total;
        }

        lblAmount.setText(Double.toString(amount));
    }

    public void setProductName(String name) {
        lblName.setText(name);
    }

    public void setcategory(String category) {
        lblCategory.setText(category);
    }

    public void setProductID(String id) {
        productID = id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSaveGRN;
    private javax.swing.JButton btnSelectProduct;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSupplierEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblGRNData;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRetailPrice;
    // End of variables declaration//GEN-END:variables
}
