/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grocery_shop_sample_1;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DILUSHA LAKSHAN
 */
public class Manage_User extends javax.swing.JFrame {

    /**
     * Creates new form Manage_User
     */
    public Manage_User() {
        initComponents();
        loadEmployeeType();
        loadUserData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        dtJoined = new com.toedter.calendar.JDateChooser();
        cmbEmployeeType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnManageAddress = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Last Name");

        btnAdd1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd1.setText("ADD");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("MANAGE USER");

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel5.setText("User Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel8.setText("Contact");

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel9.setText("Joined Date");

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel10.setText("NIC");

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel11.setText("Employee Type");

        txtFName.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtLName.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtUserName.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtContact.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        txtNIC.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        cmbEmployeeType.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N

        tblUser.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "User Name", "Password", "Email", "Contact", "Joined Date", "NIC", "Type"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        btnAdd.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnManageAddress.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        btnManageAddress.setText("MANAGE ADDRESS");
        btnManageAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAddressActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\Images\\AURORA.png")); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon("E:\\Images\\AURORA.png")); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon("E:\\Images\\AURORA.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbEmployeeType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNIC, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtContact, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtLName, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(txtFName)
                                            .addComponent(dtJoined, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnManageAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(438, 438, 438)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(439, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addComponent(dtJoined, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmbEmployeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(18, 18, 18)
                        .addComponent(btnManageAddress))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(245, 245, 245)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            String fName = txtFName.getText();
            String lName = txtLName.getText();
            String userName = txtUserName.getText();
            String password = txtPassword.getText();
            String contact = txtContact.getText();
            String email = txtEmail.getText();
            
            SimpleDateFormat dtFormat = new SimpleDateFormat("yyyy-MM-dd");
            String joinedDate = dtFormat.format(dtJoined.getDate());
            
            String nic = txtNIC.getText();
            String eType = String.valueOf(cmbEmployeeType.getSelectedItem());
            
            if(fName.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the First Name");
            }else if(fName.length() > 50){
                JOptionPane.showMessageDialog(rootPane, "First Name must be less than 50 characters");
            }else if(lName.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the Last Name");
            }else if(lName.length() > 50){
                JOptionPane.showMessageDialog(rootPane, "Last Name must be less than 50 characters");
            }else if(userName.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the User Name");
            }else if(userName.length() > 10){
                JOptionPane.showMessageDialog(rootPane, "User Name must be less than 10 characters");
            }else if(password.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the Password");
            }else if(password.length() < 8 || password.length() > 16){
                JOptionPane.showMessageDialog(rootPane, "Password must have 8 - 16 characters");
            }else if(contact.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the contact number");
            }else if(contact.length() != 10){
                JOptionPane.showMessageDialog(rootPane, "Contact Number must have 10 characters");
            }else if(email.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the Email");
            }else if(email.length() > 50){
                JOptionPane.showMessageDialog(rootPane, "Email ID must be less than 50 characters");
            }else if(joinedDate.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Select the Joined Date");
            }else if(nic.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the NIC number");
            }else if(nic.length() != 13){
                JOptionPane.showMessageDialog(rootPane, "NIC must have 13 characters");
            }else if(eType.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Select the employee type");
            }else{
                ResultSet rs = dbConnection.execute("SELECT * FROM `employee` WHERE `userName`='"+userName+"'");
                if(rs.next()){
                    JOptionPane.showMessageDialog(rootPane, "This user name has been alredy used. Try another user name");
                }else{
                    ResultSet eTypeRS = dbConnection.execute("SELECT * FROM `employee_type` WHERE `type`='"+eType+"'");
                    if(eTypeRS.next()){
                        int eTypeId = eTypeRS.getInt("id");
                        ResultSet employeeRS = dbConnection.execute("INSERT INTO `employee` (`userName`,`f_name`,`l_name`,`password`,`contact`,`email`,`joined_date`,`nic`,`employee_type_id`) VALUES ('"+userName+"','"+fName+"','"+lName+"','"+password+"','"+contact+"','"+email+"','"+joinedDate+"','"+nic+"','"+eTypeId+"')");
                        JOptionPane.showMessageDialog(rootPane, "Insertion Successful");
                        loadUserData();
                    } 
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            String fName = txtFName.getText();
            String lName = txtLName.getText();
            String userName = txtUserName.getText();
            String password = txtPassword.getText();
            String contact = txtContact.getText();
            String email = txtEmail.getText();
            
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String jDate = dateFormat.format(dtJoined.getDate());
            
            String nic = txtNIC.getText();
            String eType = String.valueOf(cmbEmployeeType.getSelectedItem());
            
            if(fName.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the First Name");
            }else if(lName.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the Last Name");
            }else if(userName.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the User Name");
            }else if(password.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the Password");
            }else if(password.length() < 8 || password.length() > 16){
                JOptionPane.showMessageDialog(rootPane, "Password must have 8 - 16 characters");
            }else if(contact.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the contact number");
            }else if(contact.length() != 10){
                JOptionPane.showMessageDialog(rootPane, "Contact Number must have 10 characters");
            }else if(email.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the Email");
            }else if(jDate.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Select the Joined Date");
            }else if(nic.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Enter the NIC number");
            }else if(eType.isEmpty() == true){
                JOptionPane.showMessageDialog(rootPane, "Select the employee type");
            }else{
                ResultSet rs = dbConnection.execute("SELECT * FROM `employee` WHERE `userName`='"+userName+"'");
                if(rs.next()){
                    ResultSet eTypeRS = dbConnection.execute("SELECT * FROM `employee_type` WHERE `type`='"+eType+"'");
                    if(eTypeRS.next()){
                        int eTypeId = eTypeRS.getInt("id");
                        ResultSet employeeRS = dbConnection.execute("UPDATE `employee` SET `f_name`='"+fName+"', `l_name`='"+lName+"', `password`='"+password+"', `contact`='"+contact+"', `email`='"+email+"', `employee_type_id`='"+eTypeId+"' WHERE `userName`='"+userName+"'");
                        JOptionPane.showMessageDialog(rootPane, "Successfully Updated");
                        loadUserData();
                    }
                }else{
                     JOptionPane.showMessageDialog(rootPane, "This user name could not found. Try the correct User Name");
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnManageAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAddressActionPerformed
        if(txtUserName.getText().isEmpty() == true){
            JOptionPane.showMessageDialog(rootPane, "Enter the user name");
        }else{
            //go to the ManageAddress page
        }
    }//GEN-LAST:event_btnManageAddressActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        try{
            DefaultTableModel tblModel = (DefaultTableModel)tblUser.getModel();
            int selectedRowIndex = tblUser.getSelectedRow();
            
            txtFName.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
            txtLName.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
            txtUserName.setText(tblModel.getValueAt(selectedRowIndex, 2).toString());
            txtPassword.setText(tblModel.getValueAt(selectedRowIndex, 3).toString());
            txtEmail.setText(tblModel.getValueAt(selectedRowIndex, 4).toString());
            txtContact.setText(tblModel.getValueAt(selectedRowIndex, 5).toString());
            txtNIC.setText(tblModel.getValueAt(selectedRowIndex, 7).toString());
            cmbEmployeeType.setSelectedItem(tblModel.getValueAt(selectedRowIndex, 9).toString());
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_User().setVisible(true);
            }
        });
    }
    
    //load employee types to the combo box
    private void loadEmployeeType(){
        try{
            ResultSet eRS = dbConnection.execute("SELECT * FROM `employee_type`");
            while(eRS.next()){
                String type = eRS.getString("type");
                cmbEmployeeType.addItem(type);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }
    
    //load all users to the table
    private void loadUserData(){
        try{
            clearEmployeeData();
            ResultSet userRS = dbConnection.execute("SELECT * FROM `employee`");
            while(userRS.next()){
                String fName = userRS.getString("f_name");
                String lName = userRS.getString("l_name");
                String userName = userRS.getString("userName");
                String password = userRS.getString("password");
                String contact = userRS.getString("contact");
                String email = userRS.getString("email");
                String jDate = userRS.getString("joined_date");
                String nic = userRS.getString("nic");
                String eTypeID = String.valueOf(userRS.getInt("employee_type_id"));
                
                String tbData[] = {fName,lName,userName,password,email,contact,jDate,nic,eTypeID};
                DefaultTableModel model = (DefaultTableModel)tblUser.getModel();
                model.addRow(tbData);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }
    
    //clear all data in the table
    private void clearEmployeeData(){
        //code here
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnManageAddress;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbEmployeeType;
    private com.toedter.calendar.JDateChooser dtJoined;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
